name: Build Docker image
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install package manager
        run: corepack enable
      - name: Install dependencies
        run: pnpm i
      - name: Prepare build
        run: pnpm run prepare:build
      - name: Build docker image
        run: "docker build . -f ./Dockerfile -t ${{ secrets.DOCKER_REPO_URL }}/zwoo-docs:latest"
      - name: Login to gitea
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REPO_URL}}
          username: ${{ secrets.DOCKER_REPO_USER }}
          password: ${{ secrets.DOCKER_REPO_PASS }}
      - name: Push image
        run: "docker push ${{ secrets.DOCKER_REPO_URL }}/zwoo-docs:latest"
